name: erasing_invisible_watermarks
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.14
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anyio==4.8.0
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - beautifulsoup4==4.13.3
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - clip==1.0
    - coloredlogs==15.0.1
    - contourpy==1.3.1
    - cycler==0.12.1
    - datasets==3.4.1
    - decorator==5.2.1
    - diffusers==0.32.2
    - dill==0.3.8
    - distro==1.9.0
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastapi==0.115.11
    - ffmpy==0.5.0
    - filelock==3.17.0
    - flatbuffers==25.2.10
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - ftfy==6.3.1
    - gdown==5.2.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - gradio==5.21.0
    - gradio-client==1.7.2
    - groovy==0.1.2
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.29.1
    - humanfriendly==10.0
    - idna==3.10
    - imageio==2.37.0
    - importlib-metadata==8.6.1
    - ipython==8.34.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - jiter==0.8.2
    - joblib==1.4.2
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - ldm==0.1.3
    - lightning-utilities==0.12.0
    - lpips==0.1.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.2.0
    - multiprocess==0.70.16
    - narwhals==1.31.0
    - networkx==3.4.2
    - numpy==2.2.3
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - onnx==1.17.0
    - onnxruntime-gpu==1.21.0
    - open-clip-torch==2.31.0
    - openai==1.63.2
    - opencv-python==4.11.0.86
    - orjson==3.10.15
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - patsy==1.0.1
    - pexpect==4.9.0
    - pillow==11.1.0
    - plotly==6.0.1
    - plotly-express==0.4.1
    - prompt-toolkit==3.0.50
    - propcache==0.3.0
    - protobuf==6.30.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==19.0.1
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydub==0.25.1
    - pygments==2.19.1
    - pyparsing==3.2.1
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.0
    - python-multipart==0.0.20
    - pytz==2025.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - ruff==0.11.0
    - safehttpx==0.1.6
    - safetensors==0.5.2
    - scikit-image==0.25.2
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - semantic-version==2.10.0
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - starlette==0.46.1
    - statsmodels==0.14.4
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tifffile==2025.2.18
    - timm==1.0.14
    - tokenizers==0.21.1
    - tomlkit==0.13.2
    - torch==2.6.0
    - torchmetrics==1.6.1
    - torchvision==0.21.0
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.49.0
    - triton==3.2.0
    - typer==0.15.2
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - urllib3==2.3.0
    - uvicorn==0.34.0
    - wcwidth==0.2.13
    - websockets==15.0.1
    - xxhash==3.5.0
    - yarl==1.18.3
    - zipp==3.21.0
